### ISSUE TITLE
Question: E-Mail Configuration

### ISSUE THREAD

**Issue by liszca** [bit-bots/imagetagger#199]
What is to be configured for mails beeing sent?

Is it enough to configure an email account with postfix, which could be a gmail account?

**Comment by ftsell** [comment]
It depends on your setup.

In our setup we have configured the following two environment variables:
```
IT_EMAIL_HOST=<hostname of mailserver>
IT_DEFAULT_FROM_EMAIL=<an email address>
```
For us, this is enough because the email server allows unauthenticated mails to be sent from trusted hosts and imagetagger is running on one such trusted host.

---

Generally the following environment variables are available (defined in [settings.py](https://github.com/bit-bots/imagetagger/blob/master/imagetagger/imagetagger/settings.py#L228-L232)):
```
IT_EMAIL_HOST (required)
IT_EMAIL_PORT
IT_EMAIL_HOST_USER
IT_EMAIL_HOST_PASSWORD
IT_DEFAULT_FROM_EMAIL

**Comment by liszca** [comment]
Thanks!
