### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by crazyliyi** [bit-bots/imagetagger#54]
Hello, I git clone this repository and install the required dependencies. But when I type "python3 manage.py runserver 134.100.14.61:5432" on my terminal, I get "Is the server running on host "134.100.14.61" and accepting TCP/IP connections on port 5432?" Is there a user-guide for who want to try this tool?

**Comment by Daniel451** [comment]
Preferred way of using the tool (for emphasizing collaboration) is simply using our hosted service at: https://imagetagger.bit-bots.de/
This allows for ease of use and also easy collaboration between different teams.

If you'd like to self-host your own instance you are of course also welcome and allowed to do so. However (due to limited resources) we can not offer hard-/software support for self-hosted instances.

Maybe @NFiedler has an idea what could cause your error...or you'll just try our hosted service ;)

**Comment by NFiedler** [comment]
Please make sure to set up the required PostgeSql Database and adapt the setup.py accordingly. A user-guide does not exist at the moment. 
Some questions about how to use the runserver script are explained [here](https://stackoverflow.com/questions/5768797/manage-py-runserver) and in the [Django doku](https://docs.djangoproject.com/en/2.0/ref/django-admin/#runserver). 
Please note that the runserver script is a way to run the instance for test and development purposes. [Here](https://github.com/fsinfuhh/mafiasi-rkt/tree/master/imagetagger) an rkt container is provided, which is used for our public instance.

**Comment by veyvin** [comment]
Can I use sqlite , and not valid email address when Create a new user

**Comment by NFiedler** [comment]
The tool uses a PostgreSQL JSONB-Field to store the label vectors. So you can't switch to SQLite without heavy adaptations there. 

With 02a47f63c4ea2705cca7551e8eed6ec8b2b8f63a we started to use [django-registration](https://django-registration.readthedocs.io/en/2.4.1/index.html). In our examle configuration, the registration mails are written to the console.

**Comment by timonegk** [comment]
In commits c03bfe22638823c7cc6fdd4518e30c9293ea0f7d and b8f0a4085999b4d9d51ec6fb12ab0d7f183eaf4c, the setup guide was improved to be more helpful. I will close the issue now. If you have further questions, feel free to ask in this issue.
