### ISSUE TITLE
BUG: similar annotation warning is not shown, js error instead

### ISSUE THREAD

**Issue by plieningerweb** [bit-bots/imagetagger#62]
How to reproduce:

label one image as "not in the image". Save label.

Now relaod page, label image again as "not in the image" and press "f" to see next image.
Nothing happens.

JS Error:
![image](https://user-images.githubusercontent.com/481107/39990011-d6e7436a-576b-11e8-9fe4-2cd77b4936df.png)

xhr response
![image](https://user-images.githubusercontent.com/481107/39990028-e482fda2-576b-11e8-8107-f7daf5f8f447.png)

**Comment by NFiedler** [comment]
Actually, "f" saves the current annotation and then changes to the next image. Use "d" to just change to the next image without saving. 
Anyway, that is no reason for the JS stuff to break completely when a similar annotation to the current one exists...

**Comment by NFiedler** [comment]
I adapted the API to be able to update the annotations of the current image. And the updating process of the annotation list.

**Comment by NFiedler** [comment]
There was a warning which was never made visible, because of the other error occurring earlier. Now, there is a light blue warning telling you that the annotation already existed. When you save after an edit, the warning is yellow, because the annotation you edited gets deleted (because the user had a reason to change it and the result he intended already exists).
