### ISSUE TITLE
Add labels to bounding boxes

### ISSUE THREAD

**Issue by mats-claassen** [bit-bots/imagetagger#95]
Hi, I have played around a bit with the tool and it has interesting features.
However, I didn't find how to add labels to annotations. I mean I can add a bounding box to an image but I cannot specify a label for that bounding box.

Am I missing something or is this feature not available?

**Comment by NFiedler** [comment]
Currently, it works the other way around. The annotation type you create defines the label. To tag tables for example, you create the annotation type "table" with a bounding box or a polygon as vector type and then you can tag tables. 
This way, you can filter easier for tags by name because it makes sure a table is called "table" and not "Table", "TABLE" or even "desk". Additionally, it allows the admin of the tool to define its use case.

**Comment by mats-claassen** [comment]
OK, thanks for the explanation
